sudo: required
services:
    - docker

before_install:
    -docker build -t alexmarroquin/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run alexmarroquin/react-test npm test -- --coverage

after_success:
    - docker build -t alexmarroquin/multi-client ./client
    - docker build -t alexmarroquin/multi-nginx ./nginx
    - docker build -t alexmarroquin/multi-server ./server
    - docker build -t alexmarroquin/multi-worker ./worker

    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    docker push alexmarroquin/multi-client
    docker push alexmarroquin/multi-nginx
    docker push alexmarroquin/multi-server
    docker push alexmarroquin/multi-worker

